version: '3.5'

services:
  database:
    image: 'postgis/postgis:latest'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    container_name: postgres
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis:/data

  redis-commander:
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:${REDIS_HOST}:${REDIS_PORT}
    ports:
      - "8081:8081"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest-docker-postgres
    env_file: .env
    environment:
      - PORT=${DOCKER_PORT}
    ports:
      - ${LOCAL_PORT}:${DOCKER_PORT}
    depends_on:
      - database
      - redis
    volumes:
      - ./src:/app/src

volumes:
  postgres-data:
  redis: